return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPost", "BufNewFile", "BufWritePost", "VeryLazy" },
    cmd = {
      "TSBufDisable",
      "TSBufEnable",
      "TSBufToggle",
      "TSDisable",
      "TSEnable",
      "TSToggle",
      "TSInstall",
      "TSInstallInfo",
      "TSInstallSync",
      "TSModuleInfo",
      "TSUninstall",
      "TSUpdate",
      "TSUpdateSync",
    },
    build = ":TSUpdate",
    opts = {
      highlight = { enable = true },
      indent = {
        enable = true,
        disable = function(_, bufnr)
          return vim.b[bufnr].large_buf
        end,
      },
      ensure_installed = {
        "astro",
        "css",
        "go",
        "html",
        "javascript",
        "typescript",
        "scss",
        "toml",
        "tsx",
        "jsdoc",
        "json",
        "diff",
        "bash",
        "c",
        "markdown",
        "markdown_inline",
        "query",
        "lua",
        "luadoc",
        "luap",
        "regex",
        "vim",
        "vimdoc",
        "rust",
        "cpp",
        "dockerfile",
        "gomod",
        "gowork",
        "gosum",
        "json5",
        "jsonc",
        "c_sharp",
        "terraform",
        "hcl",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
