local config = {
  opt = {
    backup = false,
    wildmode = "longest:full,full",
    wildmenu = true,
    undolevels = 10000,
    autowrite = true,
    formatoptions = "jcroqlnt",
    grepformat = "%f:%l:%c:%m",
    grepprg = "rg --vimgrep",
    clipboard = "unnamedplus",
    termguicolors = true,
    hlsearch = true,
    writebackup = false,
    swapfile = false,
    conceallevel = 0,
    fileencoding = "utf-8",
    wrap = false,
    virtualedit = "block",
    updatetime = 300,
    undofile = true,
    title = true,
    timeoutlen = 500,
    tabstop = 2,
    splitbelow = true,
    splitright = true,
    splitkeep = "screen",
    spelllang = { "en" },
    smartcase = true,
    smartindent = true,
    sidescrolloff = 8,
    scrolloff = 4,
    signcolumn = "yes",
    showmode = false,
    confirm = true,
    cursorline = true,
    expandtab = true,
    shiftwidth = 2,
    shiftround = true,
    relativenumber = true,
    pumheight = 10,
    pumblend = 10,
    inccommand = "nosplit",
    preserveindent = true,
    number = true,
    linebreak = true,
    mouse = "a",
    ignorecase = true,
    showcmd = false,
    ruler = false,
    laststatus = 0,
    infercase = true,
    hidden = true,
    copyindent = true,
    numberwidth = 2,
    completeopt = { "menu", "menuone", "noselect" },
    shortmess = vim.opt.shortmess + { W = true, I = true, c = true, C = true },
    foldlevel = 99,
    foldlevelstart = 99,
    foldenable = true,
  },
  g = {
    mapleader = " ",
    maplocalleader = "\\",
    loaded_netrw = 1,
    loaded_netrwPlugin = 1,
    loaded_node_provider = 0,
    loaded_perl_provider = 0,
    loaded_python3_provider = 0,
    loaded_ruby_provider = 0,
  },
}

for k, v in pairs(config) do
  for a, b in pairs(v) do
    vim[k][a] = b
  end
end
