name: lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lua-linter:
    name: "Linting with luacheck"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4

      - name: Use luacheck
        run: luarocks install luacheck

      - name: lint
        run: luacheck ./*.lua ./lua/**
