name: lint

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  lua-linter:
    name: "Linting with luacheck"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4

      - name: Use luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: make lint-lua
